services:
  db:
    image: mysql:8.0
    container_name: gem_store_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gem_store_db
      MYSQL_USER: gem_store_user
      MYSQL_PASSWORD: gem_store_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: gem_store_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development
      DATABASE_URL: mysql+aiomysql://gem_store_user:gem_store_password@gem_store_db:3306/gem_store_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: