[project]
name = "team1gc"
version = "0.1.0"
description = "Gem store"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.2",
    "gunicorn>=23.0.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.11.0",
    "uvicorn>=0.38.0",
    "uvloop>=0.22.1",
]
