FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# Default number of workers if not overridden at runtime
ENV UVICORN_WORKERS=4

# Set working directory
WORKDIR /src

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl libpq-dev \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy uv configuration files first to cache deps layer
COPY pyproject.toml uv.lock ./

# Install dependencies including dev dependencies
RUN uv sync

# Copy src and tests directories
COPY ./src ./src

# Expose the port the app runs on
EXPOSE 8000

# Run FastAPI app using Uvicorn
CMD uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers ${UVICORN_WORKERS}
